#!/bin/bash

HOST=$1
PORT=$2

if [ "$HOST" == "" ]; then
	echo "Missing HOST"
	exit 0
fi

if [ "$PORT" != "" ]; then
	VPORT="-p$PORT"
else
	VPORT=""
fi
ssh -i -t $HOST $VPORT 'wget -q -O - https://raw.githubusercontent.com/KrustyHack/ssh/master/authorized_keys_from_github.sh |/bin/bash; /bin/bash -i'
